package com.cst438.controller;

import com.cst438.domain.*;
import com.cst438.dto.EnrollmentDTO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@RestController
@CrossOrigin(origins = "http://localhost:3000")
public class StudentController {

    @Autowired
    EnrollmentRepository enrollmentRepository;

    @Autowired
    SectionRepository sectionRepository;

    @Autowired
    UserRepository userRepository;

    @Autowired
    TermRepository termRepository;

    // student gets transcript showing list of all enrollments
    // studentId will be temporary until Login security is implemented
    // example URL: /transcripts?studentId=19803
    @GetMapping("/transcripts")
    public List<EnrollmentDTO> getTranscript(@RequestParam("studentId") int studentId) {
        List<Enrollment> enrollments = enrollmentRepository.findEnrollmentsByStudentIdOrderByTermId(studentId);
        List<EnrollmentDTO> transcript = new ArrayList<>();

        for (Enrollment e : enrollments) {
            Course course = e.getSection().getCourse();
            transcript.add(new EnrollmentDTO(
                e.getEnrollmentId(),
                course.getCourseId(),
                e.getSection().getSecId(),
                course.getTitle(),
                course.getCredits(),
                e.getGrade()
            ));
        }
        return transcript;
    }

    // student gets a list of their enrollments for the given year, semester
    // user must be student
    // studentId will be temporary until Login security is implemented
    @GetMapping("/enrollments")
    public List<EnrollmentDTO> getSchedule(
            @RequestParam("year") int year,
            @RequestParam("semester") String semester,
            @RequestParam("studentId") int studentId) {

        List<Enrollment> enrollments = enrollmentRepository.findByYearAndSemesterOrderByCourseId(year, semester, studentId);
        List<EnrollmentDTO> schedule = new ArrayList<>();

        for (Enrollment e : enrollments) {
            Course course = e.getSection().getCourse();
            schedule.add(new EnrollmentDTO(
                e.getEnrollmentId(),
                course.getCourseId(),
                e.getSection().getSecId(),
                course.getTitle(),
                course.getCredits(),
                e.getGrade()
            ));
        }
        return schedule;
    }

    // student adds enrollment into a section
    // user must be student
    // return EnrollmentDTO with enrollmentId generated by database
    @PostMapping("/enrollments/sections/{sectionNo}")
    public EnrollmentDTO addCourse(
            @PathVariable int sectionNo,
            @RequestParam("studentId") int studentId) {

        Section section = sectionRepository.findById(sectionNo).orElse(null);
        if (section == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "section not found " + sectionNo);
        }

        Date today = new Date();
        if (today.before(section.getTerm().getAddDate()) || today.after(section.getTerm().getAddDeadline())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "not within add period");
        }

        Enrollment existingEnrollment = enrollmentRepository.findEnrollmentBySectionNoAndStudentId(sectionNo, studentId);
        if (existingEnrollment != null) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "student already enrolled in this section");
        }

        User student = userRepository.findById(studentId).orElse(null);
        if (student == null || !student.getType().equals("STUDENT")) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "student not found " + studentId);
        }

        Enrollment newEnrollment = new Enrollment();
        newEnrollment.setSection(section);
        newEnrollment.setUser(student);
        newEnrollment.setGrade(null);

        enrollmentRepository.save(newEnrollment);

        return new EnrollmentDTO(
                newEnrollment.getEnrollmentId(),
                section.getCourse().getCourseId(),
                section.getSecId(),
                section.getCourse().getTitle(),
                section.getCourse().getCredits(),
                newEnrollment.getGrade()
        );
    }

    // student drops a course
    // user must be student
    @DeleteMapping("/enrollments/{enrollmentId}")
    public void dropCourse(@PathVariable("enrollmentId") int enrollmentId) {

        Enrollment enrollment = enrollmentRepository.findById(enrollmentId).orElse(null);
        if (enrollment == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "enrollment not found " + enrollmentId);
        }

        Date today = new Date();
        if (today.after(enrollment.getSection().getTerm().getDropDeadline())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "past drop deadline");
        }

        enrollmentRepository.delete(enrollment);
    }
}